### ISSUE TITLE
securing jirastic

### ISSUE THREAD

**Issue by hairmare** [paza/jirastic#4]
We can't just push this into the cloud without having some security in place.

My first thought was just to add some basic_auth through nginx. I then realized that the clean way to do this would probably be by doing OAuth2 against some service.

It looks like we should discuss this a bit before implementing something fulfills our requirements. We should also check that what we implement adheres to our organizational policies.

**Comment by hairmare** [comment]
@paza any updates here?

**Comment by paza** [comment]
@hairmare there is no update to this specific task. However, this project could be an IPA for Jan, he asked me what he could do and I have some more ideas how we could make jirastic more profitable for sprint reviews. I will temporarily use jirastic locally until Jan knows about the IPA.

**Comment by hairmare** [comment]
Just keep in mind that IPAs should be kept small and dooable... Personally I feel that anything OAuthy might be too much for an IPA.

**Comment by paza** [comment]
Yep, OAuth is out of scope for the IPA :)

**Comment by hairmare** [comment]
Closing since this is an oooold issue and I have now idea where development moved to.
